issues:
  exclude-rules:
    - path: buildkite/agent.go
      linters:
        # type assertion does not need checking as this will run in linux only (via Docker)
        - forcetypeassert
    - path: src/report/annotation_test.go
      linters:
        # interface return from JSON function is A-OK
        - ireturn
    - path: src/main.go
      linters:
        # use of the `fmt.Sprintf` in `main.go` isn't that big of a worry performance-wise, we will
        # let it rock
        - perfsprint

linters:
  enable-all: true
  disable:
  - asciicheck
  - depguard
  - dupl
  - errname
  - exhaustivestruct
  - exhaustruct
  - forbidigo
  - funlen
  - gci
  - gochecknoglobals
  - gocognit
  - goconst
  - godot
  - godox
  - goerr113
  - gofumpt
  - gomnd
  - lll
  - musttag
  - nestif
  - nilnil
  - nlreturn
  - paralleltest
  - prealloc
  - revive
  - tagalign
  - tagliatelle
  - testpackage
  - unparam
  - varnamelen
  - whitespace
  - wrapcheck
  - wsl
  # deprecated linters
  - deadcode
  - golint
  - ifshort
  - interfacer
  - maligned
  - nosnakecase
  - scopelint
  - structcheck
  - varcheck

linters-settings:
  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict

  cyclop:
    max-complexity: 30

  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    default-signifies-exhaustive: true
