version: "2"
linters:
  default: all
  disable:
    - asciicheck
    - depguard
    - dupl
    - err113
    - errname
    - exhaustruct
    - forbidigo
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - godot
    - godox
    - lll
    - mnd
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - noinlineerr
    - paralleltest
    - prealloc
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 30
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      config:
        G101:
          mode: strict
        global:
          audit: disabled
          nosec: enabled
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forcetypeassert
        path: buildkite/agent.go
      - linters:
          - ireturn
        path: src/report/annotation_test.go
      - linters:
          - perfsprint
        path: src/main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
