name: ECR Scan Results
description: Retrieves scan results from ECR and can optionally fail the build.
author: https://github.com/greg-aumann
requirements:
  - docker
  - jq
configuration:
  properties:
    image-name:
      type: string
    max-criticals:
      type: string
    max-highs:
      type: string
    image-label:
      type: string
  additionalProperties: false
